services:
  - type: web
    name: hello-monolith
    env: node
    plan: free
    buildCommand: cd server && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
