name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Log in to Render API and deploy
    - name: Deploy to Render
      run: |
        curl -fsSL https://render.com/deploy/sync -X POST \
          -d '{"serviceId": "your-render-service-id"}' \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}"
