name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2
    # Log in to Render API and deploy
    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST "https://api.render.com/v1/services/DevOpsWithDocker-3_2_Deployment_pipeline_to_a_cloud_service/deploy" \
          -H "Authorization: Bearer $RENDER_API_KEY"